#!/bin/bash

IntermediateResult="$(for i in $(cat /proc/partitions | awk '{print $3,$4}' | grep -v ^1\ | grep -Eo $(basename $1)[0-9]+ | grep -Eo [0-9]+);\
                      do paste <(lsblk -blno NAME $1$i | awk '{print "/dev/"$1}')\
                               <(lsblk -blno SIZE $1$i | awk '{OFMT="%.0f";print ($1/1024)}')\
                               <(lsblk -blno FSTYPE $1$i | sed 's/^$/~~~~~/')\
                               <(sgdisk -p $1 | grep '  '$i' ' | awk '{print $6}')\
                               <(sgdisk -p $1 | grep -q '  '$i' ' || echo -ne ~~~~)\
                               <(lsblk -blno LABEL $1$i | sed 's/^$/~~~~~/;s/ /~.~/g'); done)"


if [ "$2" = "--efi-filter" ] || [ "$2" = "-e" ] || [ "$3" = "--efi-filter" ] || [ "$3" = "-e" ]

  then
    #exclude iso9600
    IntermediateResult="$(sed 's| /dev|\n/dev|g' <<<$IntermediateResult | grep -v ' iso9660 ')"

    #exclude EFI System partition
    IntermediateResult="$(sed 's| /dev|\n/dev|g' <<<$IntermediateResult | grep -v ' EF00 ')"

    #exclude Microsoft reserved partition
    IntermediateResult="$(sed 's| /dev|\n/dev|g' <<<$IntermediateResult | grep -v ' 0C01 ')"

    #exclude Microsoft recovery partition(s)
    IntermediateResult="$(sed 's| /dev|\n/dev|g' <<<$IntermediateResult | grep -v ' 2700 ')"
    
  else
    :
fi

if [ "$2" = "--real-type-name" ] || [ "$2" = "-r" ] || [ "$3" = "--real-type-name" ] || [ "$3" = "-r" ]
  then
    :
    
  else
    #for Linux GPT Partitions (8300) strip off the partition type (ext3, ext4, etc.) so they're named just 'Linux 8300'
    IntermediateResult="$(sed 's| /dev|\n/dev|g' <<<$IntermediateResult | sed 's/\(.*\) \(.*\) 8300 /\1 Linux 8300 /')"

    #rename hfsplus to HPFS    
    IntermediateResult="$(sed 's| /dev|\n/dev|g' <<<$IntermediateResult | sed 's/hfsplus/HPFS/')"

    #rename vfat to FAT32  
    IntermediateResult="$(sed 's| /dev|\n/dev|g' <<<$IntermediateResult | sed 's/vfat/FAT32/')"

    #Linux GPT Partitions created with older versions of GParted are identified as a 'Basic data partition' (0700),
    # the same as NTFS partitions, so rename them to 'Linux 8300'   
    IntermediateResult="$(sed 's| /dev|\n/dev|g' <<<$IntermediateResult | \
                        sed -r 's/(btrfs|ext2|ext3|ext4|jfs|nilfs2|reiser4|reiserfs|ufs|xfs) 0700/Linux 8300/')"
fi

sed 's| /dev|\n/dev|g' <<<$IntermediateResult | awk '{print $1,$2,$3,$4,$5}' | column -t

exit 0
